# Generated by Django 4.1.6 on 2023-02-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="portfolio/images/")),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
